/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.5

For download info, please visit:
http://www.lilacsoul.revility.com    */

//Put this OnEnter
void main()
{

object oPC = GetPCSpeaker();

if (!GetIsPC(oPC)) return;

//if (GetTag(GetItemInSlot(INVENTORY_SLOT_LEFTRING, oPC)) != "storering")
//if (GetTag(GetItemInSlot(INVENTORY_SLOT_RIGHTRING, oPC)) != "storering")
//   return;

object oTarget;
location lTarget;
oTarget = GetWaypointByTag("_ebl_to_cellar");

lTarget = GetLocation(oTarget);

//only do the jump if the location is valid.
//though not flawless, we just check if it is in a valid area.
//the script will stop if the location isn't valid - meaning that
//nothing put after the teleport will fire either.
//the current location won't be stored, either

if (GetAreaFromLocation(lTarget)==OBJECT_INVALID) return;

oTarget=GetFirstFactionMember(oPC, FALSE);

AssignCommand(oPC, ClearAllActions());

AssignCommand(oPC, ActionJumpToLocation(lTarget));
}

